base:
 batch_size: 512
 num_workers: 16
 start_epoch: 0
 epochs: 100
 data_dir_path: "./dataset"
 log_dir_path: "./checkpoint"
 dataset: "CIFAR10"
 save_num_epochs: 1
 img_size: 32
 optimizer: "Adam"
 weight_decay: 1.0e-6
 temperature: 0.1
 resnet: "resnet50"
 normalize: True
 projection_dim: 64

logistic_regression:
 epochs: 200
 learning_rate: 0.001
 batch_size: 512
 momentum: 0.9
 img_size: 32

fine_tuning:
 learning_rate: 0.001
 batch_size: 512
 momentum: 0.9
 step_size: 10
 gamma: 0.1
 epochs: 200
 img_size: 32
