datasets: "VisDA" 
root: "./datasets"
source_dataset: ['train']
target_datasets: ['validation']
model_name: 'resnet50'
save_dir: './output'
num_classes: 0
in_features: 0
batch_size: 128
num_workers: 2
gpu: 0
manual_seed: 0
optimizer: 'SGD'
learning_rate: 1e-5
beta1: 0.9
beta2: 0.999
weight_decay: 0.01
adaptation_gamma: 10
use_tfboard: True
save_model_hist: True
disp_interval: 10
save_interval: 500
print_console: True
save_ckpts: True
resume: False
epochs: 1
