datasets: "cifar10"
root: "./datasets"
checkpoint: "./checkpoint"
feature_dim: 128
temperature: 0.5
batch_size: 512
num_workers: 16
model_name: 'resnet50'
epochs: 500
start_epoch: 0

learning_rate: 0.1 #1e-3
dropout: 0
momentum: 0.9
weight_decay: 0.01 #1e-6


pretrained: True
resume: False
# resume: "./checkpoint/log.txt"
evaluate: False
